# Generated by Django 5.0.10 on 2025-01-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=255)),
                ('UserName', models.CharField(max_length=255, unique=True)),
                ('Password', models.CharField(max_length=255)),
                ('Cedula', models.CharField(max_length=11)),
                ('Email', models.EmailField(blank=True, max_length=255, null=True)),
                ('Phone', models.CharField(blank=True, max_length=12, null=True)),
                ('Active', models.BooleanField(blank=True, null=True)),
                ('RNC', models.CharField(blank=True, max_length=20, null=True)),
                ('ComercialCompanyName', models.CharField(blank=True, max_length=255, null=True)),
                ('CompanyName', models.CharField(blank=True, max_length=255, null=True)),
                ('IsMaster', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
