# Generated by Django 5.0.10 on 2025-01-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(db_column='CategoryId', primary_key=True, serialize=False)),
                ('category_name', models.CharField(db_column='CategoryName', max_length=255)),
            ],
            options={
                'db_table': 'Categorys',
                'managed': False,
            },
        ),
    ]
