# Generated by Django 5.0.10 on 2025-01-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('sample_id', models.AutoField(db_column='SampleId', primary_key=True, serialize=False)),
                ('comercial_name', models.CharField(db_column='ComercialName', max_length=255)),
                ('product_brand', models.CharField(db_column='ProductBrand', max_length=255)),
                ('batch_code', models.CharField(db_column='BatchCode', max_length=255)),
                ('production_date', models.DateField(db_column='ProductionDate')),
                ('expiration_date', models.DateField(db_column='ExpirationDate')),
                ('quantity_units', models.IntegerField(db_column='QuantityUnits')),
                ('is_rejected', models.BooleanField(db_column='IsRejected')),
                ('origin_country', models.CharField(db_column='OriginCountry', max_length=255)),
                ('collection_date', models.DateField(db_column='CollectionDate')),
                ('temperature', models.FloatField(db_column='Temperature')),
                ('special_conditions', models.TextField(blank=True, db_column='SpecialConditions')),
            ],
            options={
                'db_table': 'Samples',
                'managed': False,
            },
        ),
    ]
