# Generated by Django 5.0.10 on 2025-01-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.AutoField(db_column='IngredientId', primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(db_column='IngredientName', max_length=255)),
            ],
            options={
                'db_table': 'Ingredients',
                'managed': False,
            },
        ),
    ]
