# Generated by Django 5.0.10 on 2025-01-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allergens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergens',
            fields=[
                ('allergen_id', models.AutoField(db_column='AllergenId', primary_key=True, serialize=False)),
                ('allergen_name', models.CharField(db_column='AllergenName', max_length=255)),
            ],
            options={
                'db_table': 'Allergens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AllergenSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'AllergenSample',
                'managed': False,
            },
        ),
    ]
